# Generated by Django 5.2.4 on 2025-08-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defectsdata',
            old_name='prority',
            new_name='priority',
        ),
    ]
