# Generated by Django 5.2.4 on 2025-08-05 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0002_rename_prority_defectsdata_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='defect_screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_img', models.ImageField(blank=True, null=True, upload_to='defects_img/')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.defectsdata')),
            ],
        ),
    ]
