# Generated by Django 5.2.4 on 2025-08-09 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0003_defect_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectsdata',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.testers'),
        ),
        migrations.AlterField(
            model_name='defectsdata',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.developers'),
        ),
    ]
